theme = "papercolor-light"

[keys.normal]
A-x = "extend_to_line_bounds"
X = "select_line_above"

[keys.select]
A-x = "extend_to_line_bounds"
X = "select_line_above"

[editor]
line-number = "relative"
bufferline = "multiple"
cursorline = true
rulers = [80,120]
true-color = true
end-of-line-diagnostics = "hint"

[editor.indent-guides]
character = "╎"
render = true

[editor.inline-diagnostics]
cursor-line = "error"
other-lines = "disable"

[editor.lsp]
auto-signature-help = false
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
