name: images

on:
  workflow_call:
  schedule:
  - cron: "0 0 * * *"
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build -f base.Dockerfile -t nichtsfrei/base:latest .
      - run: docker push nichtsfrei/base:latest
      - run: docker build -f qmk.Dockerfile -t nichtsfrei/qmk:latest .
      - run: docker push nichtsfrei/qmk:latest
